Remove Signon Plek Override In AWS
alphagov/govuk-puppet pull request #10724
Opened 2020-09-23 14:19 UTC by camdesgov

This override was added during the migration from AWS to Carrenza, to ensure
that apps hosted by different providers would still be able to communicate with
Signon.

Now that all apps are in AWS, we want them to use the internal load balancer to
connect to Signon. To do this, we must ensure they have
signon.production.govuk-internal.digital set as their Signon URL.

This is an incident action item, you can find more information about this here:
https://docs.google.com/document/d/1npjn9yQ0z_p9ie2RBikt-VpigJWoAz76pgHwNOMlZKM/edit#

2020-09-25 08:35 UTC, fredericfran-gds requested changes
I don't think this is correct. Right now all the Plek entries (except the draft-content-store ones) are overridden, which we don't want. I would suggest removing the whole If block, including the unless part, etc.

2020-09-28 09:26 UTC, camdesgov commented
> I don't think this is correct. Right now all the Plek entries (except the draft-content-store ones) are overridden, which we don't want. I would suggest removing the whole If block, including the unless part, etc.

Amended as discussed, could you take another peek?

2020-09-28 10:15 UTC, fredericfran-gds approved these changes
looks good, please test.

2020-09-28 11:50 UTC, camdesgov commented
> looks good, please test.

Arg! Tested the branch again just now in staging and loads of errors come up on the cache machines... I don't think it's just coincidence.....I'm closing this PR for now and I've updated card.

2020-09-28 11:50 UTC, closed without merging