Add Ana Castillo Botto to integration
alphagov/govuk-puppet pull request #12081
Opened 2023-05-15 17:10 UTC by anatron

2023-05-16 09:41 UTC, sivsubra-tw requested changes

2023-05-16 09:41 UTC, sivsubra-tw commented on modules/users/manifests/anacastillobotto.pp
> +  govuk_user { '<anacastillobotto>':
Hi Ana, your class and username needs to be without the angled brackets. Please refer to https://github.com/alphagov/govuk-puppet/pull/12069/commits/1b9a267dc60791f8594ff00d38331a66739f3b84 if it helps!

2023-05-26 08:31 UTC, AgaDufrat commented
CI is failing with:
```
Failures:

  1) users::anacastillobotto should have a username of the correct form
     Failure/Error: expect(uname_from_full).to eq(uname_from_email), "name in fullname(#{user[:fullname]}) must match name in email(#{user[:email]})"
       name in fullname(Ana Castillo Botto) must match name in email(ana.botto@digital.cabinet-office.gov.uk)
     # ./modules/users/spec/classes/users_spec.rb:39:in `block (3 levels) in <top (required)>'
```

2023-05-30 08:26 UTC, anatron commented on hieradata_aws/integration.yaml
> +  - anacastillobotto
@AgaDufrat Hi Aga! Thank you for letting me know! I will correct it now :) The struggle is real

2023-06-13 13:15 UTC, robinjam requested changes

2023-06-13 13:15 UTC, robinjam commented on modules/users/manifests/anabotto.pp
> +    fullname => 'Ana Castillo Botto',
```suggestion
    fullname => 'Ana Botto',
```

Unfortunately our CI requires your full name to match your email address (though I'm not sure why...)

2023-06-13 13:39 UTC, robinjam approved these changes
Tests are passing now, so LGTM!

2023-06-13 13:46 UTC, merged